### ISSUE TITLE
document how to use spack

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#4500]
I thought we have instructions on how to use spack to install ASPECT, but I couldn't find them. Either the wiki, readme, or the manual would be good.

Specifically, I am always forget how to use an existing MPI (manually edit ~/.spack/packages.yaml, sigh) and how to specify a minimal configuration of deal.II without every optional dependency.

**Comment by tjhei** [comment]
something like this might work if your system mpi is  ``mpich@3.3.2``:
```
spack install aspect ^ mpich@3.3.2 ^ dealii~petsc~arborx~gmsh~oce~assimp~ginkgo~symengine~scalapack~sundials~arpack~adol-c
```

@gassmoeller do you have any other hints?

**Comment by tjhei** [comment]
Using system MPI (here with using mpich). Create ``~/.spack/packages.yaml`` with:
```
packages:
   mpich:
     externals:
     - spec: mpich@3.3a2 %gcc@7.5.0
       prefix: /usr/
   mpi:
     buildable: false
```

Also remember ``spack compiler find`` and ``spack compilers``.
